[book]
title = "Lattice Crypto"
authors = ["Julius Zhang"]
language = "en"
multilingual = false
src = "book/src"

[build]
build-dir = "book/build"

[output.html]
default-theme = "rust"
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/juliuszhang/lattice-crypto"
edit-url-template = "https://github.com/juliuszhang/lattice-crypto/edit/main/{path}"

[output.html.search]
enable = true

